name: create-release

on:
  push:
    paths:
    - resume.json
    - hack/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.6'
    - name: Build
      run: go run hack/template.go
    - name: Release
      uses: softprops/actions-gh-release@v1
      with:
        files: |
          resume.html
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}