name: personal-site-update

on:
  release:
    types: [released]

jobs:
  copy-to-personal-site:
    runs-on: ubuntu-latest
    steps:
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: ${{ github.repository }}
        version: ${{ github.ref }}
        file: |
          resume.html
          resume.pdf
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        repository: kasuboski/personal-site
        path: personal-site
    - name: Copy files to personal-site
      run: |
        cp resume.html personal-site/static/resume.html
        cp resume.pdf personal-site/static/resume.pdf
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.personal_site_key }}
    - name: Push Changes
      run: |
        cd personal-site
        git remote rm origin || true
        git remote add origin git@github.com:kasuboski/personal-site.git
        git add --all
        git config user.email "josh.kasuboski@gmail.com"
        git config user.name "GitHub Actions"
        git commit -m "Update resume from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
        git push origin master