name: personal-site-update

on:
  push:
    branches:
    - master
    # paths:
    # - current.html

jobs:
  copy-to-personal-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: resume
    - uses: actions/checkout@v2
      with:
        repository: kasuboski/personal-site
        path: personal-site
    - name: Copy HTML to personal-site
      run: |
        cp resume/current.html personal-site/static/resume.html
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.personal_site_key }}
    - name: Push Changes
      run: |
        cd personal-site
        git add --all
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git commit -m "Update resume from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
        git push origin master